---
  - hosts: web
    sudo: yes
    user: root
    tasks:
      - name: Installs nginx web server
        apt: pkg=nginx state=installed update_cache=true
        notify:
          - start nginx

      - name: Copy Files
        copy: src=static_files/index.html dest=/usr/share/nginx/html/ mode=0644

    handlers:
      - name: start nginx
        service: name=nginx state=started